import ipotrant libraries

In [1]:
import ROOT
import math
from array import array
import numpy as np
from ROOT import gROOT, AddressOf

Welcome to JupyROOT 6.29/01


Set common variables

In [2]:
read_ampt_dat_files = True
use_root_ttree = False

ampt_files_path = "/home/yoren/bnl/AMPT/Artem_heau/output_taxi/"

N_files = 200

Define structures

In [3]:
gROOT.ProcessLine(
"struct event {\
  Int_t           number;\
  Int_t         ncharge_y;\
  Float_t         phi_bbc;\
  Float_t         phi_cnt;\
  Float_t         phi_fvtx;\
  Float_t         glx;\
  Float_t         gly;\
  Float_t         glz;\
  Int_t           clust_near;\
  Float_t         hit_near;\
  Float_t         pass_effcuts;\
  Float_t         alpha;\
  Float_t         beta;\
  Float_t         norm_charge;\
  Float_t         d_tr;\
  Float_t         dx_tr;\
  Float_t         dy_tr;\
  Float_t         d_cl;\
  Float_t         dx_cl;\
  Float_t         dy_cl;\
  Float_t         dx_hit;\
  Float_t         dy_hit;\
  Int_t           onedge;\
  Float_t         lx_err;\
  Float_t         ly_err;\
  };"
); 


class event:
  
  def __init__(self, input_array):
    self.number = int(input_array[0])-101
    self.check = int(input_array[1])
    self.nch_tot = int(input_array[2])
    self.bimp = float(input_array[3])
    self.npart1 = int(input_array[4])
    self.npart2 = int(input_array[5])
    self.ncoll_ell = int(input_array[6])
    self.ncoll = int(input_array[7])
    self.ncoll1 = int(input_array[8])
    self.ncharge_y = int(input_array[9])
    self.phi_bbc = float(input_array[10])
    self.phi_cnt = float(input_array[11])
    self.phi_fvtx = float(input_array[12])
  
  
  def __str__(self):
    return f"number = {self.number}, check = {self.check}, nch_tot = {self.nch_tot}, bimp = {self.bimp}, npart1 = {self.npart1}, npart2 = {self.npart2}, "+f"ncoll_ell = {self.ncoll_ell}, ncoll = {self.ncoll}, ncoll1 = {self.ncoll1}, ncharge_y = {self.ncharge_y}, phi_bbc = {self.phi_bbc}, phi_cnt = {self.phi_cnt}, phi_fvtx = {self.phi_fvtx},"
  
  def get_values(self):
    list = [self.number, self.ncharge_y, self.phi_bbc, self.phi_cnt, self.phi_fvtx]
    arr = np.array(list)
    return arr
  
class particles:
  def __init__(self):
    self.px = []
    self.py = []
    self.pz = []
    self.m = []

  def __str__(self):
    return f"N_part = {len(self.m)}"

  def add_particle(self, input_mom):
    self.px.append(float(input_mom[0]))
    self.py.append(float(input_mom[1]))
    self.pz.append(float(input_mom[2]))
    self.m.append(float(input_mom[3]))

Create TTree creator

In [4]:
def ttree_creator(name):
    tree = ROOT.TTree(name,name)
    N=5
    npa = np.array(N*[ 0.2 ])
    tree.Branch('nparrayb', npa, 'nparrayb[' + str(N) + ']/D')
    #tree.Branch("point",event,"number:check:nch_tot/i:bimp/F:npart1:npart2:ncoll_ell:ncoll:ncoll1:ncharge_y/I:phi_bbc:phi_cnt:phi_fvtx/F")
    return tree


Create file reader

In [14]:
def file_reader(filename, tree):
    f = open(filename, "r")
    for line in f:
        line = line.split()
        if float(line[0]) > 100:
            test = event(line)
            npa = test.get_values()
            print(npa)
            tree.Fill()
            part = particles()
        else :
            part.add_particle(line)
            print(part)
            


Read AMPT files and create TTree

In [15]:
tree = ttree_creator("yolo")
filename = ampt_files_path+"ampt_1.dat"
file_reader(filename,tree)

[ 0.000e+00  3.900e+01  7.540e-02  7.029e-01 -5.700e-03]
N_part = 1
N_part = 2
N_part = 3
N_part = 4
N_part = 5
N_part = 6
N_part = 7
N_part = 8
N_part = 9
N_part = 10
N_part = 11
N_part = 12
N_part = 13
N_part = 14
N_part = 15
N_part = 16
N_part = 17
N_part = 18
N_part = 19
N_part = 20
N_part = 21
N_part = 22
N_part = 23
N_part = 24
N_part = 25
N_part = 26
N_part = 27
N_part = 28
N_part = 29
N_part = 30
N_part = 31
N_part = 32
N_part = 33
N_part = 34
N_part = 35
[ 1.     28.      0.9728 -0.9532  0.7868]
N_part = 1
N_part = 2
N_part = 3
N_part = 4
N_part = 5
N_part = 6
N_part = 7
N_part = 8
[ 2.     11.     -1.1521 -1.288   1.314 ]
N_part = 1
N_part = 2
[ 3.      8.      0.3792 -0.5026  0.4681]
N_part = 1
[ 4.      6.      1.4209  0.0308 -1.3906]
N_part = 1
N_part = 2
N_part = 3
[ 5.      5.     -1.2818 -0.4302 -1.1065]
N_part = 1
N_part = 2
N_part = 3
N_part = 4
N_part = 5
N_part = 6
N_part = 7
N_part = 8
[6.     7.     0.7662 1.4599 1.2359]
N_part = 1
N_part = 2
N_part = 3
N_part = 4

In [13]:
tree.Print()
output_file = ROOT.TFile.Open("HeAu_Artem.root","RECREATE")
tree.Write()
output_file.Close()

NameError: name 'part' is not defined

******************************************************************************
*Tree    :yolo      : yolo                                                   *
*Entries :     2500 : Total =          101126 bytes  File  Size =      47356 *
*        :          : Tree compression factor =   2.12                       *
******************************************************************************
*Br    0 :nparrayb  : nparrayb[5]/D                                          *
*Entries :     2500 : Total  Size=     100831 bytes  File Size  =      47356 *
*Baskets :        4 : Basket Size=      32000 bytes  Compression=   2.12     *
*............................................................................*


In [8]:
inFile = ROOT.TFile.Open('HeAu_Artem.root')
tree_read = inFile.Get("yolo")


In [9]:
a = np.array(5*[ 0.2 ])
tree_read.SetBranchAddress('nparrayb', a)
tree_read.GetEntry(2495)
print(a)
inFile.Close()

[ 2.4950e+03  5.2000e+01 -1.1212e+00 -1.4655e+00 -1.1160e+00]


In [10]:
import math

def angle(vector1, vector2):
    x1, y1, z1 = vector1[1], vector1[2], vector1[3]
    x2, y2, z2 = vector2[1], vector2[2], vector2[3]
    inner_product = x1*x2 + y1*y2 + z1*z2
    len1 = math.hypot(x1, y1, z1)
    len2 = math.hypot(x2, y2, z2)
    #print(inner_product,len1,len2)
    rel = inner_product/(len1*len2)
    if abs(rel)>1:
        rel = 1
    return math.acos(rel)

veto_angle = math.atan(20./522)
print(veto_angle)

0.03829544464261488


In [11]:
def inv_mass(vector1, vector2):
    e1, px1, py1, pz1 = vector1[0], vector1[1], vector1[2], vector1[3]
    e2, px2, py2, pz2 = vector2[0], vector2[1], vector2[2], vector2[3]
    m2 = (e1+e2)**2 - (px1+px2)**2 - (py1+py2)**2 - (pz1+pz2)**2
    if m2<0: m2=0
    return math.sqrt(m2)

In [12]:
#second(156,5000)
import multiprocess as mp

Ntr = nThread
Nev = nEvents
seed0 = 15156
seed_iter = 43324

pn_ids = [int(2212), int(2112)]

projectile_params = [pn_ids[int(1.34*i/(Ntr))] for i in range(Ntr)]
target_params = [pn_ids[min(int(4*i/Ntr), 1)] for i in range(Ntr)]
print(projectile_params, target_params)

pool = mp.Pool(Ntr)
hist_array = pool.starmap(pythia8_runner, [(seed0+i*seed_iter, Nev, 2212, 2212) for i in range(Ntr)])
#hist_array = pool.starmap(pythia8_runner, [(seed0+i*seed_iter, Nev, 1000020040, 1000791970) for i in range(Ntr)]) #1000020030
#hist_array = pool.starmap(pythia8_runner, [(seed0+i*seed_iter, Nev, projectile_params[i], target_params[i]) for i in range(Ntr)])
pool.close()

NameError: name 'nThread' is not defined

In [ ]:
hist_Nch = hist_array[0][0]
for i in range(1, Ntr):
    hist_Nch.Add(hist_array[i][0])
hist_pt = hist_array[0][1]
for i in range(1, Ntr):
    hist_pt.Add(hist_array[i][1])
hist_imass = hist_array[0][2]
for i in range(1, Ntr):
    hist_imass.Add(hist_array[i][2])
hist_Nch_mid = hist_array[0][3]
for i in range(1, Ntr):
    hist_Nch_mid.Add(hist_array[i][3])

NameError: name 'hist_array' is not defined